<?php
// +----------------------------------------------------------------------
// | 海豚PHP框架 [ DolphinPHP ]
// +----------------------------------------------------------------------
// | 版权所有 2016~2017 河源市卓锐科技有限公司 [ http://www.zrthink.com ]
// +----------------------------------------------------------------------
// | 官方网站: http://dolphinphp.com
// +----------------------------------------------------------------------
// | 开源协议 ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------

/**
 * 菜单信息
 */
return [
  [
    'title' => '抽奖',
    'icon' => 'fa fa-fw fa-telegram',
    'url_type' => 'module_admin',
    'url_value' => 'tgbot/lottery/index',
    'url_target' => '_self',
    'online_hide' => 0,
    'sort' => 100,
    'status' => 1,
    'child' => [
      [
        'title' => '活动管理',
        'icon' => '',
        'url_type' => 'module_admin',
        'url_value' => 'tgbot/lottery/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 1,
        'status' => 1,
        'child' => [
          [
            'title' => '活动管理',
            'icon' => 'fa fa-fw fa-gift',
            'url_type' => 'module_admin',
            'url_value' => 'tgbot/lottery/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tgbot/lottery/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tgbot/lottery/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tgbot/lottery/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tgbot/lottery/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
              ],
              [
                'title' => '快速编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tgbot/lottery/quickedit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 5,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '群组管理',
            'icon' => 'fa fa-fw fa-group',
            'url_type' => 'module_admin',
            'url_value' => 'tgbot/chat/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '删除',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tgbot/chat/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tgbot/chat/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tgbot/chat/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '快速编辑',
                'icon' => '',
                'url_type' => 'module_admin',
                'url_value' => 'tgbot/chat/quickedit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '参与人员',
            'icon' => 'fa fa-fw fa-user',
            'url_type' => 'module_admin',
            'url_value' => 'tgbot/user/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '设置机器人',
        'icon' => 'fa fa-fw fa-wrench',
        'url_type' => 'module_admin',
        'url_value' => 'tgbot/index/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 2,
        'status' => 1,
        'child' => [
          [
            'title' => '配置机器人',
            'icon' => 'fa fa-fw fa-gears',
            'url_type' => 'module_admin',
            'url_value' => 'tgbot/index/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
          ],
          [
            'title' => '设置 Webhook',
            'icon' => 'fa fa-fw fa-wrench',
            'url_type' => 'module_admin',
            'url_value' => 'tgbot/index/setwebhook',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
          [
            'title' => '移除 Webhook',
            'icon' => 'fa fa-fw fa-wrench',
            'url_type' => 'module_admin',
            'url_value' => 'tgbot/index/removewebhook',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 3,
            'status' => 1,
          ],
        ],
      ],
    ],
  ],
];
